name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  pages: write
  id-token: write

jobs:
  dependency-policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: qubit-ltd/rs-dependency-policy/.github/actions/check@230684e69896eccf7617174966e10d5decbfa115

  rust-ci:
    uses: qubit-ltd/rs-ci/.github/workflows/rust-ci.yml@ac84c7b4a439f703a6dee46faec805105ab5d714
    with:
      coverage_enforce_thresholds: "1"
    secrets: inherit
